/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import static Controller.Main.main;
import Controller.SQLite;
import Model.Session;
import Model.User;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Jay-ai
 */
public class AccountHome extends javax.swing.JPanel {
    
    public SQLite sqlite;
    private Session session;

    /**
     * Creates new form AccountHome
     */
    public AccountHome() {
        initComponents();
        
    }
    
    public void init(SQLite sqlite){
        this.sqlite = sqlite;
    }
    
    public void setSession(Session session){
        this.session = session;
        if(session != null)
            userLabel.setText(session.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changePassBtn = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();

        changePassBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        changePassBtn.setText("Change Password");
        changePassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassBtnActionPerformed(evt);
            }
        });

        userLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userLabel.setText("Username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changePassBtn)
                    .addComponent(userLabel))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(userLabel)
                .addGap(18, 18, 18)
                .addComponent(changePassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void changePassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassBtnActionPerformed

        String strengthCondition = "^(?=.*[A-Z])+(?=.*[!@#$%^&*()\\-_+.])+(?=.*[0-9])+(?=.*[a-z])*.{8,}$";
        
        JTextField oldPassword = new JPasswordField();
        JTextField password = new JPasswordField();
        JTextField confpass = new JPasswordField();
        designer(oldPassword, "OLD PASSWORD");
        designer(password, "NEW PASSWORD");
        designer(confpass, "CONFIRM NEW PASSWORD");
            
        Object[] message = {
            "Enter New Password:", oldPassword, password, confpass
        };

        int result = JOptionPane.showConfirmDialog(null, message, "CHANGE PASSWORD", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null);
            
        if (result == JOptionPane.OK_OPTION) {
            //System.out.println(password.getText());
            //System.out.println(confpass.getText());
            if(!password.getText().equals(confpass.getText())){
                JOptionPane.showMessageDialog(null, "New password and confirm password must match.", "Password Change", JOptionPane.OK_OPTION);
                return;
            }
            if (!password.getText().matches(strengthCondition)){
                JOptionPane.showMessageDialog(null, "Password must have 1 uppercase letter,special character, and digit and length 8.", "Password Change", JOptionPane.OK_OPTION);
                return;
            }
            if(!sqlite.checkUserCredentials(session.getUsername(),oldPassword.getText())){
                JOptionPane.showMessageDialog(null, "Please enter your current password.", "Password Change", JOptionPane.OK_OPTION);
                return;
            }
            
                
            
            Random random = new Random();
            byte[] salt = new byte[16];
            random.nextBytes(salt);
            String newPass  = sqlite.hashPassword(password.getText().toCharArray(),salt);
            
            sqlite.updatePassword(session.getUsername(), newPass);
            sqlite.addLogs("PASSWORD", session.getUsername(), "Successfully changed own password", (new Timestamp(System.currentTimeMillis())).toString());
            JOptionPane.showMessageDialog(null, "Password successfully changed.", "Password Change", JOptionPane.OK_OPTION);
            
        }
    }//GEN-LAST:event_changePassBtnActionPerformed
    
    public void designer(JTextField component, String text){
        component.setSize(70, 600);
        component.setFont(new java.awt.Font("Tahoma", 0, 18));
        component.setBackground(new java.awt.Color(240, 240, 240));
        component.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        component.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), text, javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12)));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePassBtn;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
